services:
  schedule_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule_bot
    environment:
      - ENV=production
    restart: unless-stopped
    networks:
      - postgres_postgres
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M

networks:
  postgres_postgres:
    external: true